config/routes.rb
Rails.application.routes.draw do

   root 'news_feed#index'

  devise_for :brands
  devise_for :students
  
  resources :brands do
    resources :jobs 
  end
    get   'brands/:brand_id/fun' => 'jobs#fun', as: :fun
    get 'categories/infosys'
    get 'categories/wipro'
    get 'categories/accenture'
    get 'categories/amazon'
    get 'categories/cognizant'

    get 'welcomes/profile'
    get 'experiences/new'

    resources :experiences, :only => [:create, :update, :delete]
    resources :certifications, :only => [:create, :update, :delete]
    resources :courses, :only => [:create, :update, :delete]
    resources :educations, :only => [:create, :update, :delete]
    resources :projects, :only => [:create, :update, :delete]
    resources :dashboards, :only => [:create, :show, :index] 

    

  

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :jobs
	has_many :students, :through => :jobs

end

app/models/certification.rb
class Certification < ActiveRecord::Base
	belongs_to :student
end

app/models/course.rb
class Course < ActiveRecord::Base
	belongs_to :student
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
	belongs_to :student
	belongs_to :job
end

app/models/education.rb
class Education < ActiveRecord::Base
	belongs_to :student
end

app/models/experience.rb
class Experience < ActiveRecord::Base
	belongs_to :student
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :student
  belongs_to :brand
  has_many :order
  scope :infosys,-> {where(brand_id: 1)}
  scope :wipro,-> {where(brand_id: 2)}
  scope :cognizant,-> {where(brand_id: 3)}
  scope :amazon,-> {where(brand_id: 4)}
  scope :accenture,-> {where(brand_id: 5)}

  has_many :dashboards
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :student
  belongs_to :job
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :student
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :jobs
	has_many :brands, :through => :jobs
	has_many :orders
	has_many :experiences
	has_many :certifications
	has_many :educations
	has_many :courses
	has_many :projects
	serialize :skills,Array
	serialize :languages,Array

	has_many :dashboards
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
	def new
		@brand=Brand.new
	end
	def create
		@brand=Brand.create(Brand_param)
		if @brand.save
			flash[:success]="success"
			redirect_to @brand
		else
			flash[:error] = @brand.errors.full_messages
			render 'new'
	    end
    end
    def index
    	@brand=Brand.all
    end
    
    def show
    	@brand=Brand.find(params[:id])
    end
	def edit
	end
	def update
		@brand.update(brand_param)
		redirect_to '#',notice: "updated"
	end
    def destroy
    	@brand.destroy
    	redirect_to '#',notice: "deleted"
    end
	private
	def set_brand
		@brand=Brand.find(params[:id])
	end
	def brand_param
		params.require(:brand).permit(:name,:location)
	end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	
	def create
		@student=Student.find(current_student.id)
		if @student.courses.create(course_params)
			redirect_to(:controller => "welcomes", :action => "profile")
		end
	end

	private
	def course_params
		params.permit(:course_name, :course_code, :associated_with)
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def new
    @brand=current_brand
    @job=Job.new
  end

  def create
    @brand=current_brand
    @job=@brand.jobs.create(job_param)
    if @job.save
      redirect_to fun_path(@brand)
   else
    render 'new'
  end
  end

  def index
    @jobs=Job.all
  end
  def fun
    
       @brand=Brand.find(params[:brand_id])
       @jobs=@brand.jobs.all
  end
 
  def show

       @brand=Brand.find(params[:brand_id])
       @job=@brand.jobs.find(params[:id])
  end

  def edit
  end

  def update
    @brand=Brand.find(params[:brand_id])
    @job=@brand.jobs.find(params[:id])
    @job.update(job_param)
  end

  def destroy
    @brand=Brand.find(params[:brand_id])
    @job=@brand.jobs.find(params[:id])
    @job.destroy
    redirect_to brand_path(@brand),:notice => "Deleted"
  end
  private
  def job_param
    params[:brand].require(:job).permit(:profile,:duration,:stipend)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	
	def create
		@student=Student.find(current_student.id)
		if @student.projects.create(project_params)
			redirect_to(:controller => "welcomes", :action => "profile")
		end
	end

	private
	def project_params
		params.permit(:title, :occupation, :from, :to, :project_url, :description)
	end

end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  
  def profile
  	@student=Student.find(current_student.id)
  	@experiences=@student.experiences.all
  	@certifications=@student.certifications.all
  	@educations=@student.educations.all
  	@projects=@student.projects.all
  	@courses=@student.courses.all
  end

  def index
    @job=Job.all
  end

 
  private
  def student_param
    params.require(:student).permit(:name,:address,:contact,:skills,:gender)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brads_helper.rb
module BradsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/news_feed_helper.rb
module NewsFeedHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/welcomes/profile.html.erb
<div class="row">
<div class="col-sm-3"></div>
<div class="col-sm-3"><%= gravatar_tag current_student.email, :class => "img-rounded", :size => 200 %></div>
<div class="col-sm-3">
<div class="text-primary"><h2><%= current_student.name%></h2></div>
<%= current_student.email %><br>
<%= current_student.contact %><br>
</div>
</div>

<div class="row" style="margin-top: 10px">
<div class="panel panel-default">
<div class="panel-header">Experience

<div id="experience_button" type="button" class="btn add_thing" onclick="show('experience_form','experience_button')"><%= link_to "", experiences_new_path, :remote => true %></div>

</div>
<div class="panel-body panel_box">
<% @experiences.each do |e| %>
<div class="exp_company"><%= e.title %></div>
<div class=""><%= e.company_name %></div>
<%= e.location %>
<div><%= e.from %> - <%= e.to %></div>
<%= e.description %>
<br>
<% end %>	

</div>



<script type="text/javascript">
	function show(target,th){
document.getElementById(target).style.display = 'block';
document.getElementById(th).style.display = 'none';
}

function hide(target,th){
document.getElementById(target).style.display = 'none';
document.getElementById(th).style.display = 'block';
}
</script>

<div id="experience_form" hidden=true>
	<%= render "forms/experience" %>
</div>


</div>
</div>
<div class="row">
<h2>Certification</h2>

<% @certifications.each do |c| %>
<%= c.certificate_name %>
<%= c.certificate_authority %>
<%= c.license_no %>
<%= c.certification_url %>
<%= c.certification_date %>
<br>
<% end %>

<div id="certification_form" hidden="true">
<%= render "forms/certification" %>
</div>

<button id="certification_button" type="button" class="btn" onclick="show('certification_form','certification_button')"><%= link_to "Add Certification", :remote => true %></button>
</div>

<div class="row">
<h2>Education</h2>

<% @educations.each do |c| %>
<%= c.school %>
<%= c.from %>
<%= c.to %>
<%= c.degree %>
<%= c.field_of_stude %>
<%= c.grade %>
<%= c.description %>
<br>
<% end %>

<div id="education_form" hidden="true">
<%= render "forms/education" %>
</div>

<button id="education_button" type="button" class="btn" onclick="show('education_form','education_button')"><%= link_to "Add Education", :remote => true %></button>
</div>

<div class="row">
<h2>Course</h2>

<button id="clickMeId" type="button" class="btn"><%= link_to "Add Course", :remote => true %></button>
</div>

<div class="row">
<h2>Project</h2>

<% @projects.each do |c| %>
<%= c.title %>
<%= c.occupation %>
<%= c.from %>
<%= c.to %>
<%= c.project_url %>
<%= c.description %>
<br>
<% end %>

<div id="project_form" hidden="true">
<%= render "forms/project" %>
</div>

<button id="project_button" type="button" class="btn" onclick="show('project_form','project_button')"><%= link_to "Add Project", :remote => true %></button>
</div>