config/routes.rb
Rails.application.routes.draw do

   root 'news_feed#index'

  devise_for :brands
  devise_for :students
  
  resources :brands do
    resources :jobs 
  end
    get   'brands/:brand_id/fun' => 'jobs#fun', as: :fun
    get 'categories/infosys'
    get 'categories/wipro'
    get 'categories/accenture'
    get 'categories/amazon'
    get 'categories/cognizant'

    get 'welcomes/profile'
    get 'experiences/new'

    resources :experiences, :only => [:create, :update, :delete]
    resources :certifications, :only => [:create, :update, :delete]
    resources :courses, :only => [:create, :update, :delete]
    resources :educations, :only => [:create, :update, :delete]
    resources :projects, :only => [:create, :update, :delete]
    resources :dashboards, :only => [:create, :show, :index] 

    

  

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :jobs
	has_many :students, :through => :jobs

end

app/models/certification.rb
class Certification < ActiveRecord::Base
	belongs_to :student
end

app/models/course.rb
class Course < ActiveRecord::Base
	belongs_to :student
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
	belongs_to :student
	belongs_to :job
end

app/models/education.rb
class Education < ActiveRecord::Base
	belongs_to :student
end

app/models/experience.rb
class Experience < ActiveRecord::Base
	belongs_to :student
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :student
  belongs_to :brand
  has_many :order
  scope :infosys,-> {where(brand_id: 1)}
  scope :wipro,-> {where(brand_id: 2)}
  scope :cognizant,-> {where(brand_id: 3)}
  scope :amazon,-> {where(brand_id: 4)}
  scope :accenture,-> {where(brand_id: 5)}

  has_many :dashboards
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :student
  belongs_to :job
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :student
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :jobs
	has_many :brands, :through => :jobs
	has_many :orders
	has_many :experiences
	has_many :certifications
	has_many :educations
	has_many :courses
	has_many :projects
	serialize :skills,Array
	serialize :languages,Array

	has_many :dashboards
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
	def new
		@brand=Brand.new
	end
	def create
		@brand=Brand.create(Brand_param)
		if @brand.save
			flash[:success]="success"
			redirect_to @brand
		else
			flash[:error] = @brand.errors.full_messages
			render 'new'
	    end
    end
    def index
    	@brand=Brand.all
    end
    
    def show
    	@brand=Brand.find(params[:id])
    end
	def edit
	end
	def update
		@brand.update(brand_param)
		redirect_to '#',notice: "updated"
	end
    def destroy
    	@brand.destroy
    	redirect_to '#',notice: "deleted"
    end
	private
	def set_brand
		@brand=Brand.find(params[:id])
	end
	def brand_param
		params.require(:brand).permit(:name,:location)
	end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	
	def create
		@student=Student.find(current_student.id)
		if @student.courses.create(course_params)
			redirect_to(:controller => "welcomes", :action => "profile")
		end
	end

	private
	def course_params
		params.permit(:course_name, :course_code, :associated_with)
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def new
    @brand=current_brand
    @job=Job.new
  end

  def create
    @brand=current_brand
    @job=@brand.jobs.create(job_param)
    if @job.save
      redirect_to fun_path(@brand)
   else
    render 'new'
  end
  end

  def index
    @jobs=Job.all
  end
  def fun
    
       @brand=Brand.find(params[:brand_id])
       @jobs=@brand.jobs.all
  end
 
  def show

       @brand=Brand.find(params[:brand_id])
       @job=@brand.jobs.find(params[:id])
  end

  def edit
  end

  def update
    @brand=Brand.find(params[:brand_id])
    @job=@brand.jobs.find(params[:id])
    @job.update(job_param)
  end

  def destroy
    @brand=Brand.find(params[:brand_id])
    @job=@brand.jobs.find(params[:id])
    @job.destroy
    redirect_to brand_path(@brand),:notice => "Deleted"
  end
  private
  def job_param
    params[:brand].require(:job).permit(:profile,:duration,:stipend)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	
	def create
		@student=Student.find(current_student.id)
		if @student.projects.create(project_params)
			redirect_to(:controller => "welcomes", :action => "profile")
		end
	end

	private
	def project_params
		params.permit(:title, :occupation, :from, :to, :project_url, :description)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brads_helper.rb
module BradsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/news_feed_helper.rb
module NewsFeedHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/forms/_certification.html.erb
<h2>Add Certification</h2>

<%= form_tag(:controller => "certifications", :action => "create", :method => "post") do %>

  <div class="field">
    <%= label_tag(:certificate_name, "Certification Name") %><br />
    <%= text_field_tag(:certificate_name) %>
  </div>
  <div class="field">
    <%= label_tag(:certificate_authority, "Certification Authority") %><br />
    <%= text_field_tag(:certificate_authority) %>
  </div>
  <div class="field">
    <%= label_tag(:license_no, "License Number") %><br />
    <%= text_field_tag(:license_no) %>
  </div>
  <div class="field">
    <%= label_tag(:certification_url, "Certification url") %><br/>
    <%= text_field_tag(:certification_url) %>
  </div>
  <div class="field">
    <%= label_tag(:certification_date, "Certificate Date") %><br />
    <%= datetime_local_field(:certificate, :certification_date) %>
  </div>

  <div class="actions">
    <%= submit_tag("Save") %>
  </div>
<% end %>

<button id="cancel" type="button" class="btn" onclick="hide('certification_form', 'certification_button')">Cancel</button>

app/views/forms/_course.html.erb
<h2>Add Experience</h2>

<%= form_tag(:controller => "courses", :method => "create", :action => "post") do %>

  <div class="field">
    <%= label_tag(:company_name) %><br />
    <%= text_field_tag(:company_name) %>
  </div>
  <div class="field">
    <%= label_field(:title) %><br />
    <%= text_field_tag(:title) %>
  </div>
  <div class="field">
    <%= label_field(:location) %><br />
    <%= text_field_tag(:location) %>
  </div>
  <div class="field">
    <%= label_field(:time_period) %><br/>
    <%= text_field_tag(:time_period) %>
  </div>
  <div class="field">
    <%= label_field(:description) %><br />
    <%= text_field_tag(:description) %>
  </div>

  <div class="actions">
    <%= submit_tag("Save") %>
  </div>
<% end %>
<button id="cancel" type="button" class="btn" onclick="hide('experience_form','course_button')">Cancel</button>

app/views/forms/_education.html.erb
<h2>Add Education</h2>

<%= form_tag(:controller => "educations", :action => "create", :method => "post") do %>

  <div class="field">
    <%= label_tag(:company_name) %><br />
    <%= text_field_tag(:company_name) %>
  </div>
  <div class="field">
    <%= label_tag(:title) %><br />
    <%= text_field_tag(:title) %>
  </div>
  <div class="field">
    <%= label_tag(:location) %><br />
    <%= text_field_tag(:location) %>
  </div>
  <div class="field">
    <%= label_tag(:time_period) %><br/>
    <%= text_field_tag(:time_period) %>
  </div>
  <div class="field">
    <%= label_tag(:description) %><br />
    <%= text_field_tag(:description) %>
  </div>

  <div class="actions">
    <%= submit_tag("Save") %>
  </div>
<% end %>
<button id="cancel" type="button" class="btn" onclick="hide('education_form','education_button')">Cancel</button>

app/views/forms/_experience.html.erb
<h2>Add Experience</h2>

<%= form_tag(:controller => "experiences", :action => "create", :method => "post") do  %>

  <div class="field">
    <%= label_tag(:company_name) %><br />
    <%= text_field_tag(:company_name) %>
  </div>
  <div class="field">
    <%= label_tag(:title) %><br />
    <%= text_field_tag(:title) %>
  </div>
  <div class="field">
    <%= label_tag(:location) %><br />
    <%= text_field_tag(:location) %>
  </div>
  <div class="field">
    <%= label_tag(:from) %><br/>
    <%= select_date Date.today, prefix: :start_date %>
  </div>
    <div class="field">
    <%= label_tag(:to) %><br/>
    <%= select_date Date.today, prefix: :start_date %>
  </div>
  <div class="field">
    <%= label_tag(:description) %><br />
    <%= text_field_tag(:description) %>
  </div>

  <div class="actions">
    <%= submit_tag("Save") %>
  </div>
<% end %>
<button id="cancel" type="button" class="btn" onclick="hide('experience_form','experience_button')">Cancel</button>

app/views/forms/_project.html.erb
<h2>Add Project</h2>

<%= form_tag(:controller => "projects", :action => "create", :method => "post") do  %>

  <div class="field">
    <%= label_tag(:company_name) %><br />
    <%= text_field_tag(:company_name) %>
  </div>
  <div class="field">
    <%= label_tag(:Title) %><br />
    <%= text_field_tag(:title) %>
  </div>
  <div class="field">
    <%= label_tag(:Location) %><br />
    <%= text_field_tag(:location) %>
  </div>
  <div class="field">
    <%= label_tag(:time_period) %><br/>
    <%= text_field_tag(:time_period) %>
  </div>
  <div class="field">
    <%= label_tag(:description) %><br />
    <%= text_field_tag(:description) %>
  </div>

  <div class="actions">
    <%= submit_tag("Save") %>
  </div>
<% end %>

<button id="cancel" type="button" class="btn" onclick="hide('project_form','project_button')">Cancel</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Internbazaar</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Internbazaar", root_url, class: "navbar-brand" %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
        <% if student_signed_in? %>
        <li><%= link_to 'Dashboard', {:controller => "dashboards", :action => "index"} %></li>
        <li><%= link_to 'Internships', brand_jobs_path(:brand_id) %></li>
        <%elsif brand_signed_in? %>
        <li>
        <%= link_to 'New Job', new_brand_job_path(:brand_id) %>
        </li>
        <%end%>
        </ul>

          <ul class="nav navbar-nav pull-right">
          <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          categories
          <span class="caret"></span>
          </a>

          <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'Infosys', categories_infosys_path %></li>
          <li><%= link_to 'Amazon', categories_amazon_path %></li>
          <li><%= link_to 'Wipro', categories_wipro_path %></li>
          <li><%= link_to 'Cognizant', categories_cognizant_path %></li>
          <li><%= link_to 'Accenture', categories_accenture_path %></li>
          </ul></li>
          <% if student_signed_in? %>
          <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">

          <%= gravatar_tag current_student.email, :size => 20 %>

          <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'Profile', welcomes_profile_path %></li>
          <li><%= link_to 'Log out', destroy_student_session_path, method: :delete %></li>

          </ul>
          </li>
          <% elsif brand_signed_in? %>
          <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">

          <%= gravatar_tag current_brand.email, :size => 20 %>

          <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'Profile', edit_brand_registration_path %></li>
          <li><%= link_to 'Log out', destroy_brand_session_path, method: :delete %></li>

          </ul>
          </li>
          <%else %>


          <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">

          Log_in

          <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'Student', new_student_session_path %></li>
          <li><%= link_to 'Company', new_brand_session_path %></li>

          </ul>
          </li>
          <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">

          Sign_in

          <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'Student', new_student_registration_path %></li>
          <li><%= link_to 'Company', new_brand_registration_path%></li>

          </ul>
          </li>
          <% end %>




          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container" style="max-width: 800px">

    <div class="row">
    <div class="col-lg-12 text-center">
    <%flash.each do |a, b| %>
    <div class="alert alert-success"><%= b %></div>
    <% end %>
    <%= yield %>
    </div>
    </div>
    </div>
    <!--/.container -->
    <style>body{padding-top:70px;}</style>

  </body>
  </html>